# Generated by Django 4.2.7 on 2023-11-10 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('contact', 'contact')], max_length=128, null=True)),
                ('key', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
