# Generated by Django 4.2.7 on 2023-11-09 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company_link_companyphone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Branch',
        ),
        migrations.RenameModel(
            old_name='CompanyPhone',
            new_name='BranchPhone',
        ),
        migrations.RenameField(
            model_name='branchphone',
            old_name='company',
            new_name='brach',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='company',
            new_name='branch',
        ),
    ]
