# Generated by Django 4.2.7 on 2023-11-09 06:43

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_company_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchphone',
            name='brach',
        ),
        migrations.RemoveField(
            model_name='link',
            name='branch',
        ),
        migrations.AddField(
            model_name='branch',
            name='key',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='links',
            field=models.ManyToManyField(blank=True, related_name='branches', to='core.link'),
        ),
        migrations.AddField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='phones',
            field=models.ManyToManyField(blank=True, related_name='branches', to='core.branchphone'),
        ),
        migrations.AddField(
            model_name='branchphone',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='7757', max_length=128, null=True, region=None),
        ),
    ]
