# Generated by Django 4.2.7 on 2023-11-10 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_branch_unique_id_branchphone_unique_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='branchphone',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='country',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='district',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='link',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='location',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='measurment',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='position',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='region',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='servicephoto',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='video',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='village',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='visitphoto',
            name='unique_id',
        ),
    ]
