# Generated by Django 4.2.7 on 2023-11-10 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_branch_new_branchphone_new_category_new_comment_new_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='new',
        ),
        migrations.RemoveField(
            model_name='branchphone',
            name='new',
        ),
        migrations.RemoveField(
            model_name='category',
            name='new',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='new',
        ),
        migrations.RemoveField(
            model_name='country',
            name='new',
        ),
        migrations.RemoveField(
            model_name='district',
            name='new',
        ),
        migrations.RemoveField(
            model_name='link',
            name='new',
        ),
        migrations.RemoveField(
            model_name='location',
            name='new',
        ),
        migrations.RemoveField(
            model_name='measurment',
            name='new',
        ),
        migrations.RemoveField(
            model_name='order',
            name='new',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='new',
        ),
        migrations.RemoveField(
            model_name='position',
            name='new',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='new',
        ),
        migrations.RemoveField(
            model_name='region',
            name='new',
        ),
        migrations.RemoveField(
            model_name='service',
            name='new',
        ),
        migrations.RemoveField(
            model_name='servicephoto',
            name='new',
        ),
        migrations.RemoveField(
            model_name='video',
            name='new',
        ),
        migrations.RemoveField(
            model_name='village',
            name='new',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='new',
        ),
        migrations.RemoveField(
            model_name='visitphoto',
            name='new',
        ),
    ]
