# Generated by Django 4.2.7 on 2023-11-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_branch_new_remove_branchphone_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='clients',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='experience',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
